### ISSUE TITLE
nginx cant be build with 2.0 version

### ISSUE THREAD

**Issue by destinqo** [arut/nginx-dav-ext-module#36]
../nginx-dav-ext-module/ngx_http_dav_ext_module.c: In function ‘ngx_http_dav_ext_depth’:
../nginx-dav-ext-module/ngx_http_dav_ext_module.c:616:26: error: ‘ngx_http_headers_in_t’ has no member named ‘depth’
     depth = r->headers_in.depth;
                          ^
make[1]: *** [objs/addon/nginx-dav-ext-module/ngx_http_dav_ext_module.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/root/BUILD/nginx/nginx-1.14.2'
make: *** [build] Error 2

**Comment by destinqo** [comment]
with version 0.1.0 it works.

**Comment by destinqo** [comment]
yes, thanks i already find that this was a problem :). thank
